// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovoSei.Infrastructure.Data;

#nullable disable

namespace NovoSei.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607032204_AddBlocosReuniao")]
    partial class AddBlocosReuniao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlocosReuniaoProcessos", b =>
                {
                    b.Property<int>("BlocoReuniaoId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessosId")
                        .HasColumnType("int");

                    b.HasKey("BlocoReuniaoId", "ProcessosId");

                    b.HasIndex("ProcessosId");

                    b.ToTable("BlocosReuniaoProcessos");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Assinatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssinadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Assinaturas");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.BlocoReuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GeradoraUnidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("GeradoraUnidadeId");

                    b.ToTable("BlocosReuniao");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.BlocoReuniaoUnidade", b =>
                {
                    b.Property<int>("BlocoReuniaoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeReceptoraId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DevolvidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BlocoReuniaoId", "UnidadeReceptoraId");

                    b.HasIndex("UnidadeReceptoraId");

                    b.ToTable("BlocoReuniaoUnidades");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("UnidadeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ComentariosHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("NovoSei.Core.Entities.ControlePrazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DiasUteis")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("ResolvidoPorUsuarioId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("ControlePrazos");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaminhoArquivoPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConteudoHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TemplateDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.HasIndex("TemplateDocumentoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Documentos");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DocumentosHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Feriado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .IsUnique();

                    b.ToTable("Feriados");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Marcador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Marcadores");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("MarcadoresHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Orgao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Orgaos");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("OrgaosHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSequencial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSequencial")
                        .IsUnique();

                    b.HasIndex("UnidadeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Processos");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProcessosHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("NovoSei.Core.Entities.TemplateDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ConteudoHtmlBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TemplatesDocumento");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OrgaoId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentUnidadeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentUnidadeId");

                    b.HasIndex("OrgaoId", "Sigla")
                        .IsUnique();

                    b.ToTable("Unidades");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UnidadesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DoisFatoresHabilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmailAlternativo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Segredo2Fa")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Token2FaAtivacao")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("TokenEmailExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProcessosMarcadores", b =>
                {
                    b.Property<int>("MarcadorId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("MarcadorId", "ProcessoId");

                    b.HasIndex("ProcessoId");

                    b.ToTable("ProcessosMarcadores");
                });

            modelBuilder.Entity("UsuariosUnidades", b =>
                {
                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UnidadeId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosUnidades");
                });

            modelBuilder.Entity("BlocosReuniaoProcessos", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.BlocoReuniao", null)
                        .WithMany()
                        .HasForeignKey("BlocoReuniaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Processo", null)
                        .WithMany()
                        .HasForeignKey("ProcessosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Assinatura", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Documento", "Documento")
                        .WithMany("Assinaturas")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Usuario", "Usuario")
                        .WithMany("Assinaturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.BlocoReuniao", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Unidade", "GeradoraUnidade")
                        .WithMany()
                        .HasForeignKey("GeradoraUnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("GeradoraUnidade");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.BlocoReuniaoUnidade", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.BlocoReuniao", "BlocoReuniao")
                        .WithMany("BlocoUnidades")
                        .HasForeignKey("BlocoReuniaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Unidade", "UnidadeReceptora")
                        .WithMany()
                        .HasForeignKey("UnidadeReceptoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlocoReuniao");

                    b.Navigation("UnidadeReceptora");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Comentario", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Documento", "Documento")
                        .WithMany("Comentarios")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NovoSei.Core.Entities.Processo", "Processo")
                        .WithMany("Comentarios")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovoSei.Core.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Processo");

                    b.Navigation("Unidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.ControlePrazo", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Processo", "Processo")
                        .WithMany("ControlePrazos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Usuario", "ResolvidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ResolvidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovoSei.Core.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Processo");

                    b.Navigation("ResolvidoPorUsuario");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Documento", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Processo", "Processo")
                        .WithMany("Documentos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.TemplateDocumento", "TemplateDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TemplateDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Processo");

                    b.Navigation("TemplateDocumento");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Marcador", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Processo", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Unidade", "Unidade")
                        .WithMany("Processos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovoSei.Core.Entities.Usuario", "Usuario")
                        .WithMany("Processos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Unidade", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Orgao", "Orgao")
                        .WithMany("Unidades")
                        .HasForeignKey("OrgaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Unidade", "ParentUnidade")
                        .WithMany("ChildUnidades")
                        .HasForeignKey("ParentUnidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Orgao");

                    b.Navigation("ParentUnidade");
                });

            modelBuilder.Entity("ProcessosMarcadores", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Marcador", null)
                        .WithMany()
                        .HasForeignKey("MarcadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Processo", null)
                        .WithMany()
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsuariosUnidades", b =>
                {
                    b.HasOne("NovoSei.Core.Entities.Unidade", null)
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovoSei.Core.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NovoSei.Core.Entities.BlocoReuniao", b =>
                {
                    b.Navigation("BlocoUnidades");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Documento", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Orgao", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Processo", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("ControlePrazos");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.TemplateDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Unidade", b =>
                {
                    b.Navigation("ChildUnidades");

                    b.Navigation("Processos");
                });

            modelBuilder.Entity("NovoSei.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Assinaturas");

                    b.Navigation("Processos");
                });
#pragma warning restore 612, 618
        }
    }
}
